export const personalInfo = {
  name: 'Aadithya A R',
  shortName: 'AAR',
  initials: 'A',
  tagline: 'Engineering Intelligence at Scale',
  subtitles: [
    'ML Engineer & GenAI Builder',
    'Production RAG Architect',
    'LLM Systems Developer',
    'FAANG-Track ML Engineer',
    'B.Tech CSE (AI & ML) @ GAT',
  ],
  email: 'aadithyaar22@gmail.com',
  github: 'https://github.com/Aadithyaar22',
  linkedin: 'https://www.linkedin.com/in/aadithya-a-r/',
  leetcode: 'https://leetcode.com/u/Aadithya_AR/',
  twitter: 'https://x.com/AadithyaAR1',
  instagram: 'https://instagram.com/aadithya_ar',
  location: 'Bengaluru, India',
  college: 'Global Academy of Technology',
  degree: 'B.Tech CSE (AI & ML)',
  batch: '2022 – 2026',
  resumeUrl: '/resume.pdf',
  bio: [
    "I don't just build AI models — I build production-grade AI systems that actually ship. Currently pursuing B.Tech in CSE with AI & ML specialization at Global Academy of Technology, Bengaluru, I've spent the last two years bridging the gap between academic research and real-world deployments.",
    "My work spans Retrieval-Augmented Generation pipelines with SHAP-based explainability, autonomous code review agents on GCP, medical AI for Parkinson's detection, and real-time sign language recognition. Every project is production-first: tracked with W&B, evaluated rigorously, and deployed to cloud.",
    "I'm on a deliberate track toward MAANG as an ML Engineer. The path runs through strong fundamentals, systems thinking, and a relentless bias for building. Currently grinding LeetCode alongside shipping GenAI projects — because great ML engineers write great code.",
  ],
  philosophy: '"Build AI systems that solve real problems, measured in production, not just on paper."',
}

export const stats = [
  { value: 20, suffix: '+', label: 'GitHub Repos' },
  { value: 6, suffix: '+', label: 'Production Projects' },
  { value: 8, suffix: '+', label: 'AI/ML Stacks Used' },
  { value: 100, suffix: '+', label: 'LeetCode Solved' },
]

export const skills = {
  'AI & ML': [
    { name: 'PyTorch', level: 88, icon: '🔥' },
    { name: 'TensorFlow', level: 82, icon: '📊' },
    { name: 'Scikit-learn', level: 90, icon: '🎯' },
    { name: 'HuggingFace', level: 85, icon: '🤗' },
    { name: 'LangChain', level: 88, icon: '🔗' },
    { name: 'OpenCV', level: 80, icon: '👁️' },
    { name: 'MediaPipe', level: 78, icon: '🤚' },
    { name: 'SHAP / XAI', level: 82, icon: '💡' },
    { name: 'RAGAS', level: 78, icon: '📏' },
    { name: 'W&B', level: 85, icon: '📈' },
  ],
  'Languages': [
    { name: 'Python', level: 95, icon: '🐍' },
    { name: 'TypeScript', level: 80, icon: '📘' },
    { name: 'JavaScript', level: 78, icon: '⚡' },
    { name: 'C++', level: 75, icon: '⚙️' },
    { name: 'Bash', level: 70, icon: '🖥️' },
    { name: 'SQL', level: 72, icon: '🗄️' },
  ],
  'Systems & Cloud': [
    { name: 'FastAPI', level: 88, icon: '⚡' },
    { name: 'Next.js', level: 82, icon: '▲' },
    { name: 'React', level: 80, icon: '⚛️' },
    { name: 'Docker', level: 78, icon: '🐳' },
    { name: 'GCP / Cloud Run', level: 80, icon: '☁️' },
    { name: 'AWS Lambda', level: 72, icon: '🔶' },
    { name: 'GitHub Actions', level: 75, icon: '🔄' },
    { name: 'Node.js', level: 76, icon: '💚' },
  ],
  'Databases & Vector': [
    { name: 'ChromaDB', level: 88, icon: '🟣' },
    { name: 'Pinecone', level: 82, icon: '🌲' },
    { name: 'MongoDB', level: 78, icon: '🍃' },
    { name: 'PostgreSQL', level: 74, icon: '🐘' },
    { name: 'FAISS', level: 80, icon: '🔍' },
  ],
}

export const projects = [
  {
    id: 1,
    title: 'Adaptive RAG + XAI System',
    subtitle: 'Production-Grade GenAI',
    description: 'A fully production-ready Retrieval-Augmented Generation pipeline with SHAP-based explainability. Evaluates retrieval quality via RAGAS, tracks experiments in W&B, and delivers answers over ArXiv ML papers with attributed reasoning. Deployed as a Gradio app with 87%+ context precision.',
    longDescription: 'Built an end-to-end adaptive RAG system that selects the optimal retrieval strategy per query. Integrated SHAP-style token attribution to explain model decisions — making the system audit-ready. Achieved strong RAGAS scores with live W&B dashboards showing retrieval quality metrics.',
    tags: ['LangChain', 'ChromaDB', 'SHAP', 'W&B', 'Gradio', 'RAGAS', 'HuggingFace'],
    category: 'GenAI',
    github: 'https://github.com/Aadithyaar22/adaptive-rag-xai',
    demo: null,
    featured: true,
    impact: 'Achieved 87%+ context precision on ArXiv ML corpus',
    color: '#F59E0B',
    icon: '🧠',
  },
  {
    id: 2,
    title: 'AI Code Review Agent',
    subtitle: 'Autonomous Agentic System',
    description: 'Autonomous multi-step code review agent built with Google ADK and Gemini 2.0 Flash. Containerized with Docker, deployed to Cloud Run with full CI/CD via GitHub Actions. Reads PRs, generates structured feedback, and posts inline review comments.',
    longDescription: 'Engineered a production-deployed autonomous agent on GCP. Uses Google ADK agent framework with Gemini 2.0 Flash for reasoning. Secrets managed via GCP Secret Manager, image built via Artifact Registry, served on Cloud Run with autoscaling.',
    tags: ['Google ADK', 'Gemini 2.0', 'FastAPI', 'Docker', 'Cloud Run', 'GCP', 'GitHub Actions'],
    category: 'Agents',
    github: 'https://github.com/Aadithyaar22/ai-code-review-agent',
    demo: null,
    featured: true,
    impact: 'Live on Cloud Run — fully automated PR review pipeline',
    color: '#FF6B6B',
    icon: '🤖',
  },
  {
    id: 3,
    title: "Parkinson's Voice Detection",
    subtitle: 'Medical AI / Signal Processing',
    description: "Early Parkinson's disease detection from biomedical voice measurements using classical ML with signal processing. Feature selection pipeline narrows 22 biomarkers to 8 key predictors. SHAP attribution identifies which voice features matter most for diagnosis.",
    tags: ['Scikit-learn', 'Librosa', 'SHAP', 'Pandas', 'Seaborn', 'Python'],
    category: 'ML',
    github: 'https://github.com/Aadithyaar22/Parkinson-s_voice_detection',
    demo: null,
    featured: false,
    impact: 'High-accuracy classifier with clinically interpretable features',
    color: '#7C3AED',
    icon: '🎙️',
  },
  {
    id: 4,
    title: 'Silent Signs',
    subtitle: 'Real-Time Computer Vision',
    description: 'Real-time sign language recognition system that bridges the communication gap for the hearing impaired. Uses MediaPipe Holistic for hand landmark detection and a custom deep learning classifier for gesture recognition. Runs at 30fps on standard webcam.',
    tags: ['OpenCV', 'MediaPipe', 'TensorFlow', 'Deep Learning', 'Python'],
    category: 'CV',
    github: 'https://github.com/Aadithyaar22/Silent_signs',
    demo: null,
    featured: false,
    impact: '30fps real-time inference on CPU hardware',
    color: '#3B82F6',
    icon: '🤟',
  },
  {
    id: 5,
    title: 'AI Notebook LLM',
    subtitle: 'RAG / Knowledge Management',
    description: 'LLM-powered smart notebook that understands your notes. Ask questions across your entire knowledge base — the system retrieves semantically relevant chunks and synthesizes accurate answers. TypeScript frontend with FastAPI RAG backend.',
    tags: ['LangChain', 'RAG', 'FastAPI', 'TypeScript', 'ChromaDB', 'Next.js'],
    category: 'GenAI',
    github: 'https://github.com/Aadithyaar22/ai-notebook-llm',
    demo: null,
    featured: false,
    impact: 'Personal knowledge graph with sub-second retrieval',
    color: '#10B981',
    icon: '📓',
  },
  {
    id: 6,
    title: 'Resume Screener AI',
    subtitle: 'Agentic Workflow / NLP',
    description: 'Automated resume screening pipeline using NLP and semantic matching. Ranks candidates against job descriptions using embedding similarity and structured extraction. Reduces initial screening time from hours to seconds.',
    tags: ['Python', 'HuggingFace', 'FastAPI', 'Sentence-BERT', 'NLP'],
    category: 'ML',
    github: 'https://github.com/Aadithyaar22/resume-screener',
    demo: null,
    featured: false,
    impact: 'Automates candidate shortlisting with explainable scores',
    color: '#FBBF24',
    icon: '📋',
  },
]

export const timeline = [
  {
    year: '2022',
    type: 'education',
    title: 'B.Tech CSE (AI & ML)',
    org: 'Global Academy of Technology',
    location: 'Bengaluru, India',
    description: 'Pursuing specialization in Artificial Intelligence & Machine Learning. Core coursework in ML Theory, Deep Learning, Computer Vision, NLP, and Systems Programming.',
    highlights: ['AI & ML Specialization', 'Active ML Projects', 'Competitive Programming'],
    color: '#F59E0B',
  },
  {
    year: '2023',
    type: 'project',
    title: 'First Production ML System',
    org: "Parkinson's Voice Detection",
    location: 'Independent Research',
    description: "Built first medical AI system — detecting Parkinson's from voice biomarkers using classical ML + SHAP explainability. Laid foundation for production-first thinking.",
    highlights: ['Medical AI', 'SHAP XAI', 'Feature Engineering'],
    color: '#7C3AED',
  },
  {
    year: '2024',
    type: 'achievement',
    title: 'GenAI Pivot — RAG Systems',
    org: 'Adaptive RAG + XAI',
    location: 'Production Deployment',
    description: 'Deep dive into production RAG systems. Built Adaptive RAG with RAGAS evaluation, W&B tracking, and SHAP attribution. Live on W&B under Innomatics account with measurable benchmark scores.',
    highlights: ['RAGAS Evaluation', 'W&B Tracking', '87%+ Context Precision'],
    color: '#FF6B6B',
  },
  {
    year: '2024',
    type: 'milestone',
    title: 'Cloud Deployment Milestone',
    org: 'AI Code Review Agent on GCP',
    location: 'Google Cloud Platform',
    description: 'Deployed first fully autonomous agent to production cloud. End-to-end: Google ADK + Gemini 2.0 Flash → Docker → Artifact Registry → Cloud Run. Established cloud engineering muscle.',
    highlights: ['Cloud Run Deployment', 'Agentic Systems', 'Full CI/CD Pipeline'],
    color: '#3B82F6',
  },
  {
    year: '2025',
    type: 'current',
    title: 'FAANG ML Track — Active',
    org: 'LeetCode + Portfolio Building',
    location: 'Bengaluru, India',
    description: 'Actively targeting MAANG ML Engineer roles. Building production-grade portfolio projects, grinding DSA, and exploring multi-agent systems and Reinforcement Learning.',
    highlights: ['100+ LeetCode Solved', 'Multi-Agent RAG', 'RL Research'],
    color: '#10B981',
  },
]

export const achievements = [
  {
    icon: '🏆',
    title: 'Production RAG Deployment',
    org: 'Innomatics Research Labs',
    year: '2024',
    description: 'Adaptive RAG system with RAGAS evaluation live on W&B with 87%+ context precision on ArXiv ML papers corpus.',
    color: '#F59E0B',
  },
  {
    icon: '☁️',
    title: 'GCP Cloud Deployment',
    org: 'AI Code Review Agent',
    year: '2024',
    description: 'First autonomous agent deployed to Google Cloud Run with full CI/CD pipeline using GitHub Actions and Artifact Registry.',
    color: '#3B82F6',
  },
  {
    icon: '🤖',
    title: 'Multi-Agent RAG System',
    org: 'Innomatics Coursework',
    year: '2024',
    description: 'Built 4-agent pipeline (Orchestrator, Retriever, Synthesizer, Critic) using Claude API for advanced document understanding.',
    color: '#7C3AED',
  },
  {
    icon: '🎙️',
    title: 'Medical AI Research',
    org: "Parkinson's Detection",
    year: '2023',
    description: 'Clinical-grade ML pipeline for Parkinson\'s disease detection using voice biomarkers with SHAP-driven interpretability.',
    color: '#FF6B6B',
  },
  {
    icon: '📊',
    title: 'W&B Portfolio',
    org: 'Weights & Biases',
    year: '2024',
    description: 'Production experiment tracking with live dashboards, model versioning, and performance benchmarks across 5+ projects.',
    color: '#FBBF24',
  },
  {
    icon: '🤟',
    title: 'Real-Time CV System',
    org: 'Silent Signs',
    year: '2023',
    description: 'Real-time sign language recognition at 30fps using MediaPipe Holistic + custom deep learning — accessibility AI.',
    color: '#10B981',
  },
]

export const certifications = [
  { name: 'Google Cloud Skills Boost', issuer: 'Google', icon: '☁️' },
  { name: 'Deep Learning Specialization', issuer: 'deeplearning.ai', icon: '🧠' },
  { name: 'LangChain for LLM Apps', issuer: 'Coursera', icon: '🔗' },
  { name: 'ML with Python', issuer: 'IBM', icon: '🔬' },
  { name: 'TensorFlow Developer', issuer: 'Google', icon: '📊' },
  { name: 'FastAPI Mastery', issuer: 'Udemy', icon: '⚡' },
  { name: 'Docker & Kubernetes', issuer: 'Udemy', icon: '🐳' },
  { name: 'Prompt Engineering', issuer: 'Anthropic', icon: '✨' },
]
