export const personalInfo = {
  name: 'Aadithya A R',
  shortName: 'AAR',
  initials: 'A',
  tagline: 'Engineering Intelligence at Scale',
  subtitles: [
    'ML Engineer & GenAI Builder',
    'Google Gen AI Academy — Top 20 of 1,500+',
    'Agentic AI Intern @ Innomatics',
    'Production RAG Architect',
    'B.E. CSE (AI & ML) @ GAT',
  ],
  email: 'aadithyaar22@gmail.com',
  github: 'https://github.com/Aadithyaar22',
  linkedin: 'https://www.linkedin.com/in/aadithya-a-r/',
  leetcode: 'https://leetcode.com/u/Aadithya_AR/',
  twitter: 'https://x.com/AadithyaAR1',
  instagram: 'https://instagram.com/aadithya_ar',
  location: 'Bengaluru, India',
  college: 'Global Academy of Technology',
  degree: 'B.E. CSE (AI & ML)',
  batch: 'Oct 2023 – Jul 2027',
  cgpa: '8.47 / 10.0',
  resumeUrl: '/resume.pdf',
  bio: [
    "I work across the full applied ML lifecycle — model development, evaluation, and deployment — with a bias toward measurable performance and explainability. Currently in my B.E. in CSE (AI & ML) at Global Academy of Technology, Bengaluru, carrying a CGPA of 8.47, I build end-to-end systems in clinical ML, multimodal learning, and retrieval-augmented generation.",
    "As an ML/AI intern at Innomatics Research Labs I shipped FastAPI backends for model serving on AWS EC2 — Pydantic validation, pytest coverage, p99 under 180ms — a reusable NLP preprocessing library used across three downstream tasks, and LangChain pipelines for document-grounded QA at sub-3s inference. That work was tested at the Google Cloud Gen AI Academy APAC 2026: I completed Cohort 1, then returned for Cohort 2 and built CivicPulse AI, which finished in the Top 20 of more than 1,500 teams.",
    "Two of these projects are being written up for publication — the Parkinson's work is targeted at IEEE INDICON 2026, and the MoodScript fusion methodology at an IEEE conference. Every project here is benchmarked against a real baseline and honest about where it falls short, because that's what separates an engineer from a demo.",
  ],
  philosophy: '"Build AI systems that solve real problems, measured in production, not just on paper."',
}

export const stats = [
  { value: 20, prefix: 'Top ', suffix: '', label: 'of 1,500+ Teams' },
  { value: 8.47, suffix: '', label: 'CGPA / 10.0' },
  { value: 9, suffix: '', label: 'Production Projects' },
  { value: 7, suffix: '', label: 'Live Deployments' },
]

export const skills = {
  'AI & ML': [
    { name: 'PyTorch', level: 88, icon: '🔥' },
    { name: 'Scikit-learn', level: 90, icon: '🎯' },
    { name: 'HuggingFace (wav2vec2, BGE)', level: 88, icon: '🤗' },
    { name: 'XGBoost / LightGBM', level: 84, icon: '🌳' },
    { name: 'NumPy / Pandas', level: 90, icon: '🔢' },
    { name: 'Explainable AI (SHAP / LIME)', level: 86, icon: '💡' },
    { name: 'Transformers / ViT', level: 84, icon: '🧬' },
    { name: 'Optuna', level: 80, icon: '🎛️' },
    { name: 'Model Evaluation / CV', level: 88, icon: '📏' },
    { name: 'W&B', level: 85, icon: '📈' },
  ],
  'GenAI & RAG': [
    { name: 'LangChain', level: 88, icon: '🔗' },
    { name: 'Prompt Engineering', level: 88, icon: '✍️' },
    { name: 'RAG', level: 88, icon: '📚' },
    { name: 'Gemini / Vertex AI', level: 86, icon: '✨' },
    { name: 'ChromaDB', level: 86, icon: '🟣' },
    { name: 'BM25 / Hybrid Retrieval', level: 82, icon: '🔍' },
    { name: 'Ollama', level: 80, icon: '🦙' },
    { name: 'RAGAS', level: 80, icon: '📊' },
  ],
  'Languages & Core CS': [
    { name: 'Python', level: 95, icon: '🐍' },
    { name: 'Java', level: 78, icon: '☕' },
    { name: 'SQL', level: 80, icon: '🗄️' },
    { name: 'JavaScript / TypeScript', level: 82, icon: '📘' },
    { name: 'Data Structures & Algorithms', level: 85, icon: '🧩' },
    { name: 'OOP / DBMS / OS', level: 84, icon: '⚙️' },
  ],
  'Backend & Cloud': [
    { name: 'FastAPI', level: 90, icon: '⚡' },
    { name: 'Flask', level: 82, icon: '🌶️' },
    { name: 'RESTful APIs', level: 88, icon: '🔌' },
    { name: 'AWS (EC2, S3)', level: 82, icon: '🔶' },
    { name: 'GCP / Cloud Run', level: 86, icon: '☁️' },
    { name: 'Docker', level: 82, icon: '🐳' },
    { name: 'Git / CI-CD', level: 85, icon: '🔄' },
    { name: 'React / Next.js', level: 82, icon: '⚛️' },
  ],
  'Databases': [
    { name: 'PostgreSQL / Neon', level: 82, icon: '🐘' },
    { name: 'MongoDB Atlas', level: 80, icon: '🍃' },
    { name: 'Firestore', level: 80, icon: '🔥' },
    { name: 'Prisma', level: 78, icon: '▲' },
  ],
}

export const projects = [
  {
    id: 1,
    title: 'CivicPulse AI',
    subtitle: 'Google Gen AI Academy — Cohort 2',
    description: 'Community decision-intelligence platform for city teams, built on Gemini and Google Cloud. Ask a natural-language question about civic data and get patterns, anomalies, a decision scoreboard, and a one-click executive action memo. Finished in the Top 20 of more than 1,500 teams at the Google Cloud Gen AI Academy APAC, Cohort 2.',
    longDescription: 'Deterministic-first by design: counts, weekly trends, severity mix and z-score anomaly flags are computed in Python before Gemini ever sees the data, so the model explains real numbers instead of inventing them. The Ask AI tab gives Gemini 2.5 Pro function-calling tools that query the live DataFrame on demand, with every tool call and record count shown in an audit trace. Firestore persists brief history and reload-safe sessions; a Cloud Scheduler job runs the same pipeline weekly and emails department-scoped briefs via Cloud Functions.',
    tags: ['Gemini 2.5 Pro', 'Vertex AI', 'Cloud Run', 'Firestore', 'Cloud Functions', 'Streamlit', 'Python'],
    category: 'Agents',
    github: 'https://github.com/Aadithyaar22/CivicPulse-AI',
    demo: 'https://civicpulse-ai-474834488335.us-central1.run.app/',
    featured: true,
    award: 'Gen AI Academy · Top 20 of 1,500+',
    impact: 'Top 20 of 1,500+ teams — Google Cloud Gen AI Academy APAC, Cohort 2',
    color: '#4285F4',
    icon: '🏙️',
  },
  {
    id: 2,
    title: 'MoodScript',
    subtitle: 'Multimodal Emotion Fusion',
    description: 'A deployed journaling system that reads how you actually feel — from what you write and how you look — and responds like a therapist who remembers your patterns. Text and facial-expression classifiers each produce a distribution over seven emotions; a calibrated fusion layer combines them, and a two-pass LLM pipeline grounds every reply in the specifics of the entry.',
    longDescription: 'The research finding is the interesting part: the obvious confidence-weighted blend performed worse than the face model alone because the two classifiers were calibrated completely differently (Expected Calibration Error 0.235 for text vs 0.029 for face). Calibrated log-linear fusion fixed it, raising accuracy to 92.03% and 92.68% across two benchmarks — validated with McNemar\'s test, not just a higher number. Deployed as four independent services (React frontend, FastAPI orchestrator, text and face services) across Cloud Run and Render. Findings are being prepared as an IEEE conference paper on the fusion methodology.',
    tags: ['PyTorch', 'ViT', 'DistilRoBERTa', 'Groq LLaMA-3.3-70B', 'FastAPI', 'React', 'PostgreSQL', 'Cloud Run'],
    category: 'GenAI',
    github: 'https://github.com/Aadithyaar22/MoodScript',
    demo: 'https://moodscript-frontend-2wr445ogxq-uc.a.run.app/',
    featured: true,
    award: 'Paper in prep · IEEE',
    impact: '92.03% / 92.68% fused vs 88.4% face-only — McNemar validated',
    color: '#9D7FD4',
    icon: '🧠',
  },
  {
    id: 3,
    title: "Parkinson's",
    subtitle: 'Clinical ML Rebuild',
    description: "Detects Parkinson's disease from three seconds of vocal phonation using wav2vec2-XLS-R-300M speech embeddings with logistic regression. Started as a rebuild: the original pipeline had seven silent failures — aliased MDVP calls, NoneType hardcodes, and subject-level data leakage — and the feature extractor went from 22 to 56 dimensions (CPP, MFCCs, formants) in the process.",
    longDescription: 'Evaluated on 831 recordings from 61 subjects with 75 Optuna hyperparameter tuning trials, and validated cross-corpus across Italian and English datasets rather than held-out splits of a single corpus. Findings are being prepared for submission to a Scopus-indexed conference, targeting IEEE INDICON 2026.',
    tags: ['wav2vec2-XLS-R-300M', 'PyTorch', 'Optuna', 'XGBoost', 'LightGBM', 'praat-parselmouth', 'Flask'],
    category: 'ML',
    github: 'https://github.com/Aadithyaar22/Parkinson-s_voice_detection',
    demo: 'https://huggingface.co/spaces/Aadithya1122/parkinsons-voice-detection',
    featured: true,
    award: 'Paper in prep · IEEE INDICON 2026',
    impact: 'CV AUC 0.972 ± 0.034 · subject AUC 0.996 · 94.25% on 831 recordings',
    color: '#FF9D00',
    icon: '🎙️',
  },
  {
    id: 4,
    title: 'CardioLens',
    subtitle: 'Explainable Clinical Risk',
    description: 'Heart disease risk assessment built as a system, not a notebook. Four models with 5-fold CV and isotonic calibration produce a risk score; SHAP and LIME cross-check each other; a counterfactual shows what to change; and a 90% conformal prediction interval gives a mathematical coverage guarantee. Every prediction persists to MongoDB Atlas with a downloadable clinical PDF.',
    tags: ['Scikit-learn', 'SHAP', 'LIME', 'Conformal Prediction', 'MongoDB Atlas', 'Streamlit'],
    category: 'ML',
    github: 'https://github.com/Aadithyaar22/cardiolens',
    demo: 'https://cardiolens-heart.streamlit.app',
    featured: false,
    award: null,
    impact: 'Calibrated risk + conformal intervals, live on Streamlit Cloud',
    color: '#EF4444',
    icon: '🫀',
  },
  {
    id: 5,
    title: 'Nexus',
    subtitle: 'AI Thinking Workspace',
    description: "Multi-document RAG workspace that doesn't just answer questions about your papers — it thinks about them. Finds where documents agree and contradict, surfaces knowledge gaps with suggested learning paths, generates flashcards and exam questions, and synthesises everything into one unified mental model. Ten features, voice-enabled end to end.",
    tags: ['Next.js', 'TypeScript', 'Groq', 'RAG', 'Vector Search', 'Vercel'],
    category: 'GenAI',
    github: 'https://github.com/Aadithyaar22/Nexus',
    demo: 'https://ai-notebook-llm.vercel.app',
    featured: false,
    award: null,
    impact: 'Grounded answers with clickable citations and similarity scores',
    color: '#8B5CF6',
    icon: '📓',
  },
  {
    id: 6,
    title: 'Adaptive RAG + XAI',
    subtitle: 'Retrieval Research / MLOps',
    description: 'A document QA system over 50 real ArXiv ML papers — 1,206 chunks embedded with BGE — that routes each query before searching: BM25 for definitional questions, a 70/30 dense + BM25 hybrid for conceptual ones. SHAP provides source attribution, W&B tracks the experiments, and Mistral-7B serves locally through Ollama with no cloud GPU.',
    tags: ['LangChain', 'Mistral-7B', 'Ollama', 'ChromaDB', 'BGE Embeddings', 'SHAP', 'RAGAS', 'W&B'],
    category: 'GenAI',
    github: 'https://github.com/Aadithyaar22/adaptive-rag-xai',
    demo: 'https://aadithya1122-adaptive-rag-xai.hf.space/',
    featured: false,
    award: null,
    impact: 'RAGAS Context Precision 1.000 · Answer Relevancy 0.734',
    color: '#F59E0B',
    icon: '🧭',
  },
  {
    id: 7,
    title: 'SilentSigns',
    subtitle: 'Passive Health Screening',
    description: 'Passive neurological screening via TinyML — instead of asking someone to take a test, it reads the signals they already produce: voice tremor, gait, typing dynamics and touch patterns. Built for Cognizant Technoverse 2026 as a FastAPI + React MVP over real clinical datasets.',
    tags: ['TinyML', 'Scikit-learn', 'Signal Processing', 'FastAPI', 'React', 'Render'],
    category: 'ML',
    github: 'https://github.com/Aadithyaar22/Silent_signs',
    demo: null,
    featured: false,
    award: null,
    impact: 'Four passive biomarker streams, no active test required',
    color: '#3B82F6',
    icon: '🩺',
  },
  {
    id: 8,
    title: 'Multimodal Content Moderation',
    subtitle: 'Vision-Language Research',
    description: 'Harm detection from the relationship between image and text, not from per-modality scores. Late fusion structurally cannot catch harm that only exists jointly — two innocuous signals that together imply a threat — so this keeps raw representations alive through a cross-attention block and measures the gain against a late-fusion baseline. Framed as decision support for human moderators, not auto-removal.',
    tags: ['PyTorch', 'Cross-Attention', 'Vision-Language', 'Grad-CAM', 'SHAP'],
    category: 'CV',
    github: 'https://github.com/Aadithyaar22/multimodal-content-moderation',
    demo: null,
    featured: false,
    award: null,
    impact: 'Unimodal + late-fusion baselines done; cross-attention in progress',
    color: '#EC4899',
    icon: '🛡️',
  },
  {
    id: 9,
    title: 'UrbanBites',
    subtitle: 'Multi-Sided Platform',
    description: 'A Swiggy/Zomato-style cloud-kitchen delivery platform built as a real working product: consumer ordering flow, restaurant partner dashboard, delivery queue, and live analytics — all backed by an actual Postgres database on an actual URL, not a mockup.',
    tags: ['Next.js 16', 'TypeScript', 'Prisma', 'PostgreSQL', 'Auth.js', 'Netlify'],
    category: 'Full-Stack',
    github: 'https://github.com/Aadithyaar22/UrbanBites',
    demo: 'https://urbanbites-platform.netlify.app',
    featured: false,
    award: null,
    impact: 'Three role-specific surfaces on one live Postgres backend',
    color: '#2A78D6',
    icon: '🍽️',
  },
]

export const timeline = [
  {
    year: 'Oct 2023',
    type: 'education',
    title: 'B.E. CSE (AI & ML)',
    org: 'Global Academy of Technology',
    location: 'Bengaluru, India',
    description: 'Joined GAT for a B.E. in Computer Science Engineering with an Artificial Intelligence & Machine Learning specialization, graduating July 2027. Coursework across data structures and algorithms, OOP, DBMS, operating systems, computer networks, machine learning and deep learning.',
    highlights: ['CGPA 8.47 / 10.0', 'AI & ML Specialization', 'Graduating Jul 2027'],
    color: '#F59E0B',
  },
  {
    year: '2024 · Sep – Nov',
    type: 'project',
    title: 'Adaptive RAG with XAI + MLOps',
    org: 'Independent Research',
    location: 'Bengaluru, India',
    description: 'First serious retrieval system: document QA over 50 ArXiv ML papers with adaptive query routing between BM25 and a 70/30 dense hybrid, 1,206 chunks embedded with BGE, and Mistral-7B served locally through Ollama. SHAP handled source attribution and W&B tracked every run.',
    highlights: ['Context Precision 1.000', 'Adaptive Routing', 'W&B Tracking'],
    color: '#10B981',
  },
  {
    year: '2025 · Jan – Apr',
    type: 'project',
    title: "Parkinson's — Clinical ML Rebuild",
    org: 'Independent Research',
    location: 'Bengaluru, India',
    description: 'Rebuilt a broken clinical ML pipeline rather than starting fresh: found and fixed seven silent failures including subject-level data leakage, extended the feature extractor from 22 to 56 dimensions, and moved to wav2vec2-XLS-R-300M embeddings. Validated cross-corpus across Italian and English speech.',
    highlights: ['CV AUC 0.972 ± 0.034', '831 Recordings / 61 Subjects', 'IEEE INDICON 2026'],
    color: '#FF9D00',
  },
  {
    year: '2025 · Nov',
    type: 'achievement',
    title: '2nd Place — Departmental Project Competition',
    org: 'Global Academy of Technology',
    location: 'Bengaluru, India',
    description: 'Placed second out of 15 competing teams and 60 students in the CSE (AI & ML) departmental project competition.',
    highlights: ['2nd of 15 Teams', '60 Students', 'Departmental'],
    color: '#7C3AED',
  },
  {
    year: '2026 · Feb – Jun',
    type: 'work',
    title: 'Machine Learning / AI Intern (Agentic AI)',
    org: 'Innomatics Research Labs',
    location: 'Remote',
    description: 'Built a FastAPI backend for ML model deployment with Pydantic validation and pytest coverage, deployed on AWS EC2 with environment-based config at a p99 under 180ms. Designed a reusable NLP preprocessing library — tokenization, stemming, lemmatization, TF-IDF — used across three downstream ML tasks, and delivered two end-to-end LangChain pipelines for document-grounded QA at sub-3s inference.',
    highlights: ['p99 < 180ms on AWS EC2', 'NLP Library across 3+ Tasks', 'LangChain Pipelines'],
    color: '#EF4444',
  },
  {
    year: '2026 · Apr – Jul',
    type: 'achievement',
    title: 'Google Gen AI Academy — Cohort 1 → Cohort 2',
    org: 'Google Cloud Gen AI Academy APAC 2026',
    location: 'Google Cloud × Hack2skill · APAC',
    description: 'Completed Cohort 1 in April, then returned for Cohort 2 in July and built CivicPulse AI — a civic decision-intelligence platform on Gemini 2.5 Pro, Cloud Run, Firestore and Cloud Scheduler. It finished in the Top 20 of more than 1,500 competing teams.',
    highlights: ['Top 20 of 1,500+ Teams', 'Cohort 1 Completed', 'Gemini on Google Cloud'],
    color: '#4285F4',
  },
  {
    year: '2026 · Now',
    type: 'current',
    title: 'Multimodal Systems & MAANG Track',
    org: 'MoodScript · Content Moderation Research',
    location: 'Bengaluru, India',
    description: 'Shipping MoodScript — multimodal emotion fusion where a calibration fix turned a fusion rule that lost to its own baseline into one that beats it, now being written up for IEEE — and researching cross-attention fusion for content moderation. Targeting MAANG ML Engineer roles alongside continued DSA practice.',
    highlights: ['Calibrated Fusion', 'Cross-Attention Research', 'MAANG ML Track'],
    color: '#9D7FD4',
  },
]

export const achievements = [
  {
    icon: '🏅',
    title: 'Top 20 of 1,500+ Teams',
    org: 'Google Gen AI Academy — Cohort 2',
    year: '2026',
    description: 'CivicPulse AI finished in the Top 20 of more than 1,500 competing teams at the Google Cloud Gen AI Academy APAC, Cohort 2 — a Gemini-powered civic decision-intelligence platform running on Google Cloud.',
    color: '#4285F4',
  },
  {
    icon: '🎓',
    title: 'Gen AI Academy — Cohort 1',
    org: 'Google Gen AI Academy (APAC Edition)',
    year: '2026',
    description: 'Participated in and completed Cohort 1 of the Google Gen AI Academy, APAC Edition — the program that led directly into the Cohort 2 build and its Top-20 finish.',
    color: '#34A853',
  },
  {
    icon: '☁️',
    title: 'Full Google Cloud Stack in Production',
    org: 'CivicPulse AI',
    year: '2026',
    description: 'Cloud Run, Vertex AI, Firestore, Cloud Functions, Cloud Scheduler and Secret Manager wired into one live service — including a weekly cron that emails department-scoped briefs with nobody opening the dashboard.',
    color: '#EA4335',
  },
  {
    icon: '🎙️',
    title: 'Cross-Corpus Medical AI',
    org: "Parkinson's Detection",
    year: '2026',
    description: "Parkinson's detection from three seconds of phonation using wav2vec2-XLS-R-300M — CV AUC 0.972 ± 0.034, subject AUC 0.996, 94.25% accuracy on 831 recordings from 61 subjects. Being prepared for a Scopus-indexed conference, targeting IEEE INDICON 2026.",
    color: '#FF9D00',
  },
  {
    icon: '🧠',
    title: 'Calibration Beats the Fusion Rule',
    org: 'MoodScript',
    year: '2026',
    description: 'Diagnosed why confidence-weighted multimodal fusion lost to its own face-only baseline (ECE 0.235 vs 0.029) and fixed it with calibrated log-linear fusion — 92.03% / 92.68% across two benchmarks, validated with McNemar\'s test. Being prepared as an IEEE conference paper.',
    color: '#9D7FD4',
  },
  {
    icon: '🫀',
    title: 'Conformal Prediction in the Clinic',
    org: 'CardioLens',
    year: '2026',
    description: 'Live clinical risk platform pairing isotonic-calibrated models with SHAP + LIME cross-checks, counterfactuals, and 90% conformal intervals — a coverage guarantee, not just a confidence number.',
    color: '#EF4444',
  },
  {
    icon: '💼',
    title: 'ML / AI Internship (Agentic AI)',
    org: 'Innomatics Research Labs',
    year: '2026',
    description: 'Five-month internship (Feb–Jun 2026): FastAPI model-serving on AWS EC2 at p99 under 180ms, a reusable NLP preprocessing library used across three downstream tasks, and two LangChain pipelines for document-grounded QA at sub-3s inference.',
    color: '#7C3AED',
  },
  {
    icon: '🥈',
    title: '2nd Place — Project Competition',
    org: 'GAT Departmental, CSE (AI & ML)',
    year: '2025',
    description: 'Placed second out of 15 competing teams and 60 students in the departmental project competition at Global Academy of Technology.',
    color: '#94A3B8',
  },
  {
    icon: '📊',
    title: 'IBM Datathon — National Level',
    org: 'IBM',
    year: '2026',
    description: 'Participated in two consecutive editions of IBM\'s national-level Datathon.',
    color: '#0F62FE',
  },
]

export const certifications = [
  { name: 'Gen AI Academy APAC — Cohort 2', issuer: 'Google Cloud × Hack2skill', icon: '✨' },
  { name: 'Gen AI Academy APAC — Cohort 1', issuer: 'Google Cloud × Hack2skill', icon: '✨' },
  { name: 'Engineer AI Agents with ADK', issuer: 'Google Cloud Skill Badge', icon: '🤖' },
  { name: 'Agentic AI Internship', issuer: 'Innomatics Research Labs', icon: '💼' },
  { name: 'Data Science Essentials with Python', issuer: 'Cisco Networking Academy', icon: '🐍' },
  { name: 'Machine Learning Foundation', issuer: 'Infosys Springboard', icon: '🔬' },
]
