export const personalInfo = {
  name: 'Aadithya A R',
  shortName: 'AAR',
  initials: 'A',
  tagline: 'Engineering Intelligence at Scale',
  subtitles: [
    'ML Engineer & GenAI Builder',
    'Google Gen AI Academy — Cohort 2 · Ranked 20th',
    'Production RAG Architect',
    'LLM Systems Developer',
    'B.Tech CSE (AI & ML) @ GAT',
  ],
  email: 'aadithyaar22@gmail.com',
  github: 'https://github.com/Aadithyaar22',
  linkedin: 'https://www.linkedin.com/in/aadithya-a-r/',
  leetcode: 'https://leetcode.com/u/Aadithya_AR/',
  twitter: 'https://x.com/AadithyaAR1',
  instagram: 'https://instagram.com/aadithya_ar',
  location: 'Bengaluru, India',
  college: 'Global Academy of Technology',
  degree: 'B.Tech CSE (AI & ML)',
  batch: '2023 – 2027',
  resumeUrl: '/resume.pdf',
  bio: [
    "I don't just build AI models — I build production-grade AI systems that actually ship. Currently pursuing B.Tech in CSE with AI & ML specialization at Global Academy of Technology, Bengaluru, I've spent the last two years bridging the gap between academic research and real-world deployments.",
    "I spent three months as an Agentic AI intern at Innomatics Research Labs, shipping LangChain, LangGraph and RAG systems behind FastAPI services. That work was put to the test at the Google Cloud Gen AI Academy APAC 2026. I completed Cohort 1, then returned for Cohort 2 and built CivicPulse AI — a civic decision-intelligence platform on Gemini and Google Cloud that finished ranked 20th out of 1,500+ teams. Alongside it: multimodal emotion fusion with calibrated classifiers, cross-corpus Parkinson's detection from three seconds of speech, explainable clinical risk scoring, and multi-document RAG workspaces — all deployed, all measured.",
    "I'm on a deliberate track toward MAANG as an ML Engineer. The path runs through strong fundamentals, systems thinking, and a relentless bias for building. Every project here is live on a URL, benchmarked against a real baseline, and honest about where it falls short — because that's what separates an engineer from a demo.",
  ],
  philosophy: '"Build AI systems that solve real problems, measured in production, not just on paper."',
}

export const stats = [
  { value: 20, suffix: 'th', label: 'Google Cohort 2 Rank' },
  { value: 9, suffix: '', label: 'Production Projects' },
  { value: 7, suffix: '', label: 'Live Deployments' },
  { value: 25, suffix: '+', label: 'GitHub Repos' },
]

export const skills = {
  'AI & ML': [
    { name: 'PyTorch', level: 88, icon: '🔥' },
    { name: 'Scikit-learn', level: 90, icon: '🎯' },
    { name: 'HuggingFace', level: 88, icon: '🤗' },
    { name: 'LangChain / LCEL', level: 88, icon: '🔗' },
    { name: 'Gemini / Vertex AI', level: 88, icon: '✨' },
    { name: 'TensorFlow', level: 80, icon: '📊' },
    { name: 'SHAP / LIME / XAI', level: 86, icon: '💡' },
    { name: 'Transformers / ViT', level: 84, icon: '🧬' },
    { name: 'RAGAS', level: 78, icon: '📏' },
    { name: 'W&B / LangSmith', level: 85, icon: '📈' },
  ],
  'Languages': [
    { name: 'Python', level: 95, icon: '🐍' },
    { name: 'TypeScript', level: 84, icon: '📘' },
    { name: 'JavaScript', level: 80, icon: '⚡' },
    { name: 'C++', level: 75, icon: '⚙️' },
    { name: 'SQL', level: 76, icon: '🗄️' },
    { name: 'Bash', level: 72, icon: '🖥️' },
  ],
  'Systems & Cloud': [
    { name: 'FastAPI', level: 90, icon: '⚡' },
    { name: 'GCP / Cloud Run', level: 86, icon: '☁️' },
    { name: 'Next.js', level: 84, icon: '▲' },
    { name: 'React', level: 82, icon: '⚛️' },
    { name: 'Docker', level: 80, icon: '🐳' },
    { name: 'Streamlit', level: 85, icon: '🎈' },
    { name: 'Cloud Functions / Scheduler', level: 78, icon: '⏱️' },
    { name: 'GitHub Actions', level: 80, icon: '🔄' },
  ],
  'Databases & Vector': [
    { name: 'ChromaDB', level: 88, icon: '🟣' },
    { name: 'PostgreSQL / Neon', level: 80, icon: '🐘' },
    { name: 'Firestore', level: 80, icon: '🔥' },
    { name: 'MongoDB Atlas', level: 80, icon: '🍃' },
    { name: 'FAISS', level: 80, icon: '🔍' },
    { name: 'Pinecone', level: 78, icon: '🌲' },
  ],
}

export const projects = [
  {
    id: 1,
    title: 'CivicPulse AI',
    subtitle: 'Google Gen AI Academy — Cohort 2',
    description: 'Community decision-intelligence platform for city teams, built on Gemini and Google Cloud. Ask a natural-language question about civic data and get patterns, anomalies, a decision scoreboard, and a one-click executive action memo. Ranked 20th out of 1,500+ teams in the Google Gen AI Academy (APAC Edition), Cohort 2.',
    longDescription: 'Deterministic-first by design: counts, weekly trends, severity mix and z-score anomaly flags are computed in Python before Gemini ever sees the data, so the model explains real numbers instead of inventing them. The Ask AI tab gives Gemini 2.5 Pro function-calling tools that query the live DataFrame on demand, with every tool call and record count shown in an audit trace. Firestore persists brief history and reload-safe sessions; a Cloud Scheduler job runs the same pipeline weekly and emails department-scoped briefs via Cloud Functions.',
    tags: ['Gemini 2.5 Pro', 'Vertex AI', 'Cloud Run', 'Firestore', 'Cloud Functions', 'Streamlit', 'Python'],
    category: 'Agents',
    github: 'https://github.com/Aadithyaar22/CivicPulse-AI',
    demo: 'https://civicpulse-ai-474834488335.us-central1.run.app/',
    featured: true,
    award: 'Gen AI Academy · 20th / 1,500+',
    impact: 'Ranked 20th of 1,500+ teams — Google Gen AI Academy, Cohort 2',
    color: '#4285F4',
    icon: '🏙️',
  },
  {
    id: 2,
    title: 'MoodScript',
    subtitle: 'Multimodal Emotion Fusion',
    description: 'A deployed journaling system that reads how you actually feel — from what you write and how you look — and responds like a therapist who remembers your patterns. Text and facial-expression classifiers each produce a distribution over seven emotions; a calibrated fusion layer combines them, and a two-pass LLM pipeline grounds every reply in the specifics of the entry.',
    longDescription: 'The research finding is the interesting part: the obvious confidence-weighted blend performed worse than the face model alone (83.4% vs 88.4%) because the two classifiers were calibrated completely differently (ECE 0.235 for text vs 0.029 for face). Temperature scaling fixed it — after calibration every classical combination rule improved, and the calibrated product rule beat the face-only baseline by 3.6pp and 4.0pp across two benchmarks. Ships with LIME explanations, a rule-based crisis-safety layer, mood tracking, TTS, and clinician-readable PDF export.',
    tags: ['PyTorch', 'ViT', 'DistilRoBERTa', 'Groq Llama 3.3', 'FastAPI', 'React 19', 'Cloud Run', 'Neon'],
    category: 'GenAI',
    github: 'https://github.com/Aadithyaar22/MoodScript',
    demo: 'https://moodscript-frontend-2wr445ogxq-uc.a.run.app/',
    featured: true,
    award: null,
    impact: '92.0% / 92.7% fused accuracy vs 88.4% face-only baseline',
    color: '#9D7FD4',
    icon: '🧠',
  },
  {
    id: 3,
    title: "Parkinson's",
    subtitle: 'Medical AI / Speech',
    description: "Detects Parkinson's disease from three seconds of vocal phonation using wav2vec2-XLS-R self-supervised speech embeddings — a multilingual model that doesn't care what language the speaker uses. Validated cross-corpus across Italian and English datasets, not just held-out splits of one.",
    tags: ['wav2vec2-XLS-R', 'PyTorch', 'Scikit-learn', 'Flask', 'MongoDB', 'HuggingFace'],
    category: 'ML',
    github: 'https://github.com/Aadithyaar22/Parkinson-s_voice_detection',
    demo: 'https://huggingface.co/spaces/Aadithya1122/parkinsons-voice-detection',
    featured: true,
    award: null,
    impact: 'CV AUC 0.972 ± 0.034 · subject-level AUC 0.996 · 94.2% accuracy',
    color: '#FF9D00',
    icon: '🎙️',
  },
  {
    id: 4,
    title: 'CardioLens',
    subtitle: 'Explainable Clinical Risk',
    description: 'Heart disease risk assessment built as a system, not a notebook. Four models with 5-fold CV and isotonic calibration produce a risk score; SHAP and LIME cross-check each other; a counterfactual shows what to change; and a 90% conformal prediction interval gives a mathematical coverage guarantee. Every prediction persists to MongoDB Atlas with a downloadable clinical PDF.',
    tags: ['Scikit-learn', 'SHAP', 'LIME', 'Conformal Prediction', 'MongoDB Atlas', 'Streamlit'],
    category: 'ML',
    github: 'https://github.com/Aadithyaar22/cardiolens',
    demo: 'https://cardiolens-heart.streamlit.app',
    featured: false,
    award: null,
    impact: 'Calibrated risk + conformal intervals, live on Streamlit Cloud',
    color: '#EF4444',
    icon: '🫀',
  },
  {
    id: 5,
    title: 'Nexus',
    subtitle: 'AI Thinking Workspace',
    description: "Multi-document RAG workspace that doesn't just answer questions about your papers — it thinks about them. Finds where documents agree and contradict, surfaces knowledge gaps with suggested learning paths, generates flashcards and exam questions, and synthesises everything into one unified mental model. Ten features, voice-enabled end to end.",
    tags: ['Next.js', 'TypeScript', 'Groq', 'RAG', 'Vector Search', 'Vercel'],
    category: 'GenAI',
    github: 'https://github.com/Aadithyaar22/Nexus',
    demo: 'https://ai-notebook-llm.vercel.app',
    featured: false,
    award: null,
    impact: 'Grounded answers with clickable citations and similarity scores',
    color: '#8B5CF6',
    icon: '📓',
  },
  {
    id: 6,
    title: 'Adaptive RAG + XAI',
    subtitle: 'Retrieval Research / MLOps',
    description: 'A RAG pipeline over 50 real ArXiv ML papers that routes each query before searching — BM25 for definitional questions, dense + BM25 hybrid for conceptual ones — then applies SHAP-style ablation scoring to retrieval itself, reporting exactly which source chunk contributed what percentage of the answer. Evaluated with RAGAS, tracked in W&B, runs on Apple Silicon with no cloud GPU.',
    tags: ['LangChain', 'ChromaDB', 'Mistral-7B', 'SHAP', 'RAGAS', 'W&B', 'Gradio'],
    category: 'GenAI',
    github: 'https://github.com/Aadithyaar22/adaptive-rag-xai',
    demo: 'https://aadithya1122-adaptive-rag-xai.hf.space/',
    featured: false,
    award: null,
    impact: 'Per-chunk attribution percentages, not just cited sources',
    color: '#F59E0B',
    icon: '🧭',
  },
  {
    id: 7,
    title: 'SilentSigns',
    subtitle: 'Passive Health Screening',
    description: 'Passive neurological screening via TinyML — instead of asking someone to take a test, it reads the signals they already produce: voice tremor, gait, typing dynamics and touch patterns. Built for Cognizant Technoverse 2026 as a FastAPI + React MVP over real clinical datasets.',
    tags: ['TinyML', 'Scikit-learn', 'Signal Processing', 'FastAPI', 'React', 'Render'],
    category: 'ML',
    github: 'https://github.com/Aadithyaar22/Silent_signs',
    demo: null,
    featured: false,
    award: null,
    impact: 'Four passive biomarker streams, no active test required',
    color: '#3B82F6',
    icon: '🩺',
  },
  {
    id: 8,
    title: 'Multimodal Content Moderation',
    subtitle: 'Vision-Language Research',
    description: 'Harm detection from the relationship between image and text, not from per-modality scores. Late fusion structurally cannot catch harm that only exists jointly — two innocuous signals that together imply a threat — so this keeps raw representations alive through a cross-attention block and measures the gain against a late-fusion baseline. Framed as decision support for human moderators, not auto-removal.',
    tags: ['PyTorch', 'Cross-Attention', 'Vision-Language', 'Grad-CAM', 'SHAP'],
    category: 'CV',
    github: 'https://github.com/Aadithyaar22/multimodal-content-moderation',
    demo: null,
    featured: false,
    award: null,
    impact: 'Unimodal + late-fusion baselines done; cross-attention in progress',
    color: '#EC4899',
    icon: '🛡️',
  },
  {
    id: 9,
    title: 'UrbanBites',
    subtitle: 'Multi-Sided Platform',
    description: 'A Swiggy/Zomato-style cloud-kitchen delivery platform built as a real working product: consumer ordering flow, restaurant partner dashboard, delivery queue, and live analytics — all backed by an actual Postgres database on an actual URL, not a mockup.',
    tags: ['Next.js 16', 'TypeScript', 'Prisma', 'PostgreSQL', 'Auth.js', 'Netlify'],
    category: 'Full-Stack',
    github: 'https://github.com/Aadithyaar22/UrbanBites',
    demo: 'https://urbanbites-platform.netlify.app',
    featured: false,
    award: null,
    impact: 'Three role-specific surfaces on one live Postgres backend',
    color: '#2A78D6',
    icon: '🍽️',
  },
]

export const timeline = [
  {
    year: '2023',
    type: 'education',
    title: 'B.Tech CSE (AI & ML)',
    org: 'Global Academy of Technology',
    location: 'Bengaluru, India',
    description: 'Joined GAT to pursue a B.Tech with specialization in Artificial Intelligence & Machine Learning. Core coursework in ML theory, deep learning, computer vision, NLP, DBMS, and systems programming.',
    highlights: ['AI & ML Specialization', 'Batch of 2027', 'Competitive Programming'],
    color: '#F59E0B',
  },
  {
    year: '2025',
    type: 'project',
    title: 'Fundamentals First',
    org: 'DSA · DBMS · Applied ML',
    location: 'Coursework & Self-Study',
    description: 'Built the base before building the portfolio: data structures and algorithms, design and analysis of algorithms, relational databases, and the first applied ML notebooks. Unglamorous, and the reason everything after it holds up.',
    highlights: ['Algorithms & DSA', 'DBMS', 'First ML Models'],
    color: '#7C3AED',
  },
  {
    year: '2026 · Feb – May',
    type: 'work',
    title: 'Agentic AI Intern',
    org: 'Innomatics Research Labs',
    location: 'Hyderabad, India (Remote)',
    description: 'Three-month internship building agentic systems end to end — Python problem solving, FastAPI services, prompt engineering, LangChain, RAG pipelines, and multi-agent orchestration with LangGraph. Culminated in a 4-agent pipeline (Orchestrator, Retriever, Synthesizer, Critic) for multi-document understanding.',
    highlights: ['LangGraph & Agents', 'RAG Pipelines', 'FastAPI in Production'],
    color: '#EF4444',
  },
  {
    year: '2026 · Q2',
    type: 'achievement',
    title: 'Research-Grade Portfolio',
    org: "Parkinson's · Adaptive RAG · CardioLens · Nexus",
    location: 'Independent Research',
    description: "Four systems in one quarter, each answering a real question rather than repeating a tutorial: Parkinson's detection from 3 seconds of speech validated across two languages, SHAP-style attribution applied to retrieval instead of classification, conformal prediction intervals on clinical risk, and a multi-document RAG workspace that reasons across sources.",
    highlights: ['CV AUC 0.972', 'Retrieval Attribution', 'Conformal Prediction'],
    color: '#10B981',
  },
  {
    year: '2026 · Apr – Jul',
    type: 'achievement',
    title: 'Google Gen AI Academy — Cohort 1 → Cohort 2',
    org: 'Google Cloud Gen AI Academy APAC 2026',
    location: 'Google Cloud × Hack2skill · APAC',
    description: 'Completed Cohort 1 in April, then returned for Cohort 2 in July and built CivicPulse AI — a civic decision-intelligence platform on Gemini 2.5 Pro, Cloud Run, Firestore and Cloud Scheduler. It finished ranked 20th out of more than 1,500 competing teams.',
    highlights: ['Ranked 20th / 1,500+ Teams', 'Cohort 1 Completed', 'Gemini on Google Cloud'],
    color: '#4285F4',
  },
  {
    year: '2026 · Now',
    type: 'current',
    title: 'Multimodal Systems & MAANG Track',
    org: 'MoodScript · Content Moderation Research',
    location: 'Bengaluru, India',
    description: 'Currently shipping MoodScript — multimodal emotion fusion where temperature scaling turned a fusion rule that lost to its own baseline into one that beats it — and researching cross-attention fusion for content moderation. Targeting MAANG ML Engineer roles alongside continued DSA practice.',
    highlights: ['Calibrated Fusion', 'Cross-Attention Research', 'MAANG ML Track'],
    color: '#9D7FD4',
  },
]

export const achievements = [
  {
    icon: '🏅',
    title: 'Ranked 20th of 1,500+ Teams',
    org: 'Google Gen AI Academy — Cohort 2',
    year: '2026',
    description: 'CivicPulse AI placed 20th out of more than 1,500 competing teams in the Google Gen AI Academy (APAC Edition), Cohort 2 — a Gemini-powered civic decision-intelligence platform running on Google Cloud.',
    color: '#4285F4',
  },
  {
    icon: '🎓',
    title: 'Gen AI Academy — Cohort 1',
    org: 'Google Gen AI Academy (APAC Edition)',
    year: '2026',
    description: 'Participated in and completed Cohort 1 of the Google Gen AI Academy, APAC Edition — the program that led directly into the Cohort 2 build and its Top-20 finish.',
    color: '#34A853',
  },
  {
    icon: '☁️',
    title: 'Full Google Cloud Stack in Production',
    org: 'CivicPulse AI',
    year: '2026',
    description: 'Cloud Run, Vertex AI, Firestore, Cloud Functions, Cloud Scheduler and Secret Manager wired into one live service — including a weekly cron that emails department-scoped briefs with nobody opening the dashboard.',
    color: '#EA4335',
  },
  {
    icon: '🎙️',
    title: 'Cross-Corpus Medical AI',
    org: "Parkinson's Detection",
    year: '2026',
    description: "Parkinson's detection from three seconds of phonation using wav2vec2-XLS-R — CV AUC 0.972 ± 0.034, subject-level AUC 0.996, validated across Italian and English corpora rather than one held-out split.",
    color: '#FF9D00',
  },
  {
    icon: '🧠',
    title: 'Calibration Beats the Fusion Rule',
    org: 'MoodScript',
    year: '2026',
    description: 'Diagnosed why confidence-weighted multimodal fusion lost to its own face-only baseline (ECE 0.235 vs 0.029), fixed it with temperature scaling, and improved every classical combination rule on both benchmarks.',
    color: '#9D7FD4',
  },
  {
    icon: '🫀',
    title: 'Conformal Prediction in the Clinic',
    org: 'CardioLens',
    year: '2026',
    description: 'Live clinical risk platform pairing isotonic-calibrated models with SHAP + LIME cross-checks, counterfactuals, and 90% conformal intervals — a coverage guarantee, not just a confidence number.',
    color: '#EF4444',
  },
  {
    icon: '💼',
    title: 'Agentic AI Internship',
    org: 'Innomatics Research Labs',
    year: '2026',
    description: 'Three-month internship (Feb–May 2026) in agentic AI — LangChain, LangGraph, RAG and FastAPI — culminating in a 4-agent pipeline (Orchestrator, Retriever, Synthesizer, Critic) for multi-document understanding.',
    color: '#7C3AED',
  },
  {
    icon: '🚀',
    title: 'Seven Live Deployments',
    org: 'Cloud Run · Vercel · Netlify · HF Spaces',
    year: '2026',
    description: 'Every flagship project sits behind a public URL — Cloud Run, Vercel, Netlify, Streamlit Cloud and Hugging Face Spaces — because a system that only runs locally has not been shipped.',
    color: '#F59E0B',
  },
]

export const certifications = [
  { name: 'Gen AI Academy APAC — Cohort 2', issuer: 'Google Cloud × Hack2skill', icon: '✨' },
  { name: 'Gen AI Academy APAC — Cohort 1', issuer: 'Google Cloud × Hack2skill', icon: '✨' },
  { name: 'Engineer AI Agents with ADK', issuer: 'Google Cloud Skill Badge', icon: '🤖' },
  { name: 'Agentic AI Internship', issuer: 'Innomatics Research Labs', icon: '💼' },
  { name: 'Data Science Essentials with Python', issuer: 'Cisco Networking Academy', icon: '🐍' },
]
